import time

f = open("Korsan666.bat","w")
print("")
print("[👁‍]Youtube : SoAyHg KO")
print("")
print("[👁‍]İnstagram : Soayhg")
print("")
indir = input("[1]NO // [2]YES : ")

if indir == '1' :
	print("")
	print("[👁‍]Loding...")
	print("")
	print("[👁‍]Zararlı Dosya Yükleniyor...")
else:
	print("")
	print("Error Program Yükleme Olarak Yönlendirdi")
print("")
print("10 Saniye Sonra Yüklenicek !!!")
time.sleep(1)
print("")
print("9.99")
time.sleep(1)
print("")
print("8.99")
time.sleep(1)
print("")
print("7.99")
time.sleep(1)
print("")
print("6.99")
time.sleep(1)
print("")
print("5.99")
time.sleep(1)
print("")
print("4.99")
time.sleep(1)
print("")
print("3.99")
time.sleep(1)
print("")
print("2.99")
time.sleep(1)
print("")
print("1.99")
time.sleep(1)
print("")
print("[👁‍]Zaman Doldu Hacker :)")
print("")
print("[👁‍]Dosyayı Paylaş / Uyarı Dosya Çok Zararlı !")
print("")
print("[👁‍]Dosya İndirildi / Dosya Adı Korsan666.bat")
f.write("C:/windows/System32 deleted")
f.close()